# Generated by Django 6.0.1 on 2026-01-28 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planmember',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='planmember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('plan', 'user'), name='unique_plan_user'),
        ),
        migrations.AddConstraint(
            model_name='planmember',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_email__gt', '')), fields=('plan', 'guest_email'), name='unique_plan_guest_email'),
        ),
    ]
