# Generated by Django 6.0.1 on 2026-01-28 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_planmember_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('has_conflict', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itinerary_items', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='plans.plan')),
            ],
            options={
                'ordering': ['start_time', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_comments', to=settings.AUTH_USER_MODEL)),
                ('itinerary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plans.itineraryitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='itineraryitem',
            index=models.Index(fields=['plan', 'start_time'], name='plans_itine_plan_id_1cceba_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryitem',
            index=models.Index(fields=['start_time', 'end_time'], name='plans_itine_start_t_cab910_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryitem',
            index=models.Index(fields=['has_conflict'], name='plans_itine_has_con_db3296_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcomment',
            index=models.Index(fields=['itinerary_item', 'created_at'], name='plans_itemc_itinera_44f6ed_idx'),
        ),
    ]
